### ISSUE TITLE
[Feature Request]: Add an option to disable notifications on volume and brightness scripts

### ISSUE THREAD

**Issue by rubiin** [HyDE-Project/HyDE#17]
When using a custom osd, it does not make sense to send notification when  brightness and volume are altered. Since original hyprdots didnot have any osd, notification was only useful there

**Comment by kRHYME7** [comment]
@rubiin  Can this wait for a bit? I'm working on using ` hyde.toml`  and the hyderc will be move to `~/.local/state/` `
reason being  it's very fragile .

If we intend to add flags, It's a bad idea to add CLI --arg if the commands are used in waybar, users will need to modiy the modules. It's too tedious. 

Why not just use, env vars?
example, ROFI_SCALE , ROFI_STYLE, ROFI_NEST_STUFF 
this is neat but I hate it, it would look bloated and unorganized in the long run. 
So how about we mask that ugly env vars with toml. 

my proposal is 
having something like 

```toml
[rofi]
scale = 1
style =2 

``` 

  python now  can parse toml (stdlib) files  so we can use it as a translator. 
this way, other langugae can parse it too. 

Another thing, when the hyderc (hyde.conf in hyprdots) have syntax errors then all scripts will fail.

**Comment by rubiin** [comment]
sure thing

**Comment by kRHYME7** [comment]
@rubiin  
for now we can   manually add an entry in the ` config.toml `  
https://github.com/HyDE-Project/HyDE/blob/bca91a6721b049a14f976a2981584791788acceb/Configs/.local/share/hyde/config.toml#L104

Lemm know if you want to make this dynamic, we might consider using a lock file or IPC stuff, but this depends on how you trigger those actions.

**Comment by rubiin** [comment]
> @rubiin for now we can manually add an entry in the `config.toml`
> 
> https://github.com/HyDE-Project/HyDE/blob/bca91a6721b049a14f976a2981584791788acceb/Configs/.local/share/hyde/config.toml#L104
> 
> Lemm know if you want to make this dynamic, we might consider using a lock file or IPC stuff, but this depends on how you trigger those actions.

static is fine .
