### ISSUE TITLE
[Porting OG hyprdots]: sort prs currently in hyprdots 

### ISSUE THREAD

**Issue by abenezerw** [HyDE-Project/HyDE#18]
Make sure to have a list guys. 
1 for vital 
0 for fluff/unnecessary 
2 for up for voting it in

**Comment by abenezerw** [comment]
1 for external monitor brightness support #1771 , for people with external monitors. 
1 for pokeget instead of colorscripts #1894 I feel like kitty would load faster

**Comment by rubiin** [comment]
https://github.com/prasanthrangan/hyprdots/pull/2008

**Comment by kRHYME7** [comment]
Let's utilize the discussion panel.
