### ISSUE TITLE
[Bug]: Errors during installation

### ISSUE THREAD

**Issue by imtheabdi** [HyDE-Project/HyDE#24]
### Description

there's a few errors that pop up during installation but it succeeds anyway and the errors can be seen again when your screen locks

### Screenshots

![IMG_20241214_194811_597](https://github.com/user-attachments/assets/5b990cf9-c710-4f76-ad1c-fa25287640ba)

**Comment by kRHYME7** [comment]
@imtheabdi   Thanks!  Fixed already. there's a typo. please run ` install.sh -r `  again
