### ISSUE TITLE
[Feature Request]: Spotify icon in Hyprlock

### ISSUE THREAD

**Issue by imtheabdi** [HyDE-Project/HyDE#37]
### Description

if you go through [Hyprlock-Styles](https://github.com/MrVivekRajan/Hyprlock-Styles) you will see that in previews it shows Spotify icon when something is playing from Spotify. With the Hyprlock configuration in this repo it shows the Arch icon instead of the Spotify one. So, i was just wondering if we could have that too because it looks nicer imo.

### Use Case

in my opinion, it looks nicer and feels more intuitive that it is some information about a Spotify song instead of a random string there like other quotes.

**Comment by kRHYME7** [comment]
Iirc  (from my pr a long time ago)  I decided to use the arch icon to make it more general. How about a music glyph  🎶🎵

**Comment by Anshul-007** [comment]


**Comment by imtheabdi** [comment]
> Iirc  (from my pr a long time ago)  I decided to use the arch icon to make it more general. How about a music glyph  🎶🎵

That would be more nicer because if something is playing from YouTube it won't show the Spotify icon then too.
