### ISSUE TITLE
[Bug]: fresh install. Post installation stopped

### ISSUE THREAD

**Issue by Lofibunnygirl** [HyDE-Project/HyDE#44]
Trying to do a fresh install. At post installation the message.. Socket file not found are you sure swww-daemond is running?. Also stopping you from selecting a sddm theme and haunting the installation process. To reproduce this just install on a fresh install of arch with minimum desktop then try to install hyde project. Installed cashy os and then hyde project it worked fine tho
![20241220_154141](https://github.com/user-attachments/assets/ae812b43-f083-4ab4-9769-8593a0eae64c)

**Comment by kRHYME7** [comment]
@Lofibunnygirl  try the latest

`git pull origin master`

then rerun installation.

note that almost all Configs are installed at this stage. Only the post installation was skipped

**Comment by Lofibunnygirl** [comment]
Said uptodate shell missing
![20241220_212307](https://github.com/user-attachments/assets/51788476-1c78-4c65-85a2-7ca3a563996a)

**Comment by kRHYME7** [comment]
@Lofibunnygirl Thank you! It's just some syntax conflicts from using sh vs bash

**Comment by kRHYME7** [comment]
@Lofibunnygirl @Lofibunnygirl check latest

**Comment by Lofibunnygirl** [comment]
It updated but no shell found

**Comment by kRHYME7** [comment]
It should prompt you zsh or fish. (unless you have at least 1 of this it will skip.

can you show the error again

also be sure to run this

`git pull origin master` 


then

install.sh

**Comment by Lofibunnygirl** [comment]
![20241220_235602](https://github.com/user-attachments/assets/57284ae2-53a9-406e-99fb-dc7386aa0899)
![20241220_235510](https://github.com/user-attachments/assets/71511332-9369-49b8-83f7-f79ac5243aaf)

**Comment by kRHYME7** [comment]
Did you just press enter? or you choose 1?

**Comment by Lofibunnygirl** [comment]
Yup pressed 1 then when it ran the routine it gets to post and freezes

**Comment by imtheabdi** [comment]
I'm gonna try and repro on a VM if i can get one up.

**Comment by kRHYME7** [comment]
@imtheabdi  please provide a bash -x ./install.sh output. Thank youuu I'm confused why the Shell variable is not passed. It works on my separated user. Never tried a VM yet

**Comment by Lofibunnygirl** [comment]
I keep getting the same results now tho it won't let me choose a paru or anything..maybe I need a new arch installer?

**Comment by kRHYME7** [comment]
It won't ask that if it detected it already/ or installed.

Basically we have a list of AUR helpers then it is checked by a function if any of these are installed, if any is not yet installed , the install script will ask.

That goes with zsh too

**Comment by kRHYME7** [comment]
@Lofibunnygirl  how about manually Installing zsh?

`yay -S zsh`

**Comment by Lofibunnygirl** [comment]
Now I can't even download the repo I'm so confused

**Comment by kRHYME7** [comment]
I think you got internet connection problems. Can't cofirm yet but I'm starting a VM now. I'll check if it's HyDE's end or yours so we can narrow down the fix 

![image](https://github.com/user-attachments/assets/c58e9347-7242-4927-a10b-130b09de4bcd)

**Comment by Lofibunnygirl** [comment]
Ok it's back to no shell found

**Comment by Lofibunnygirl** [comment]
YES IT WORKS  when no shell appeared in used paru to install zsh then the bash command and now it's installing.

**Comment by Lofibunnygirl** [comment]
Thank you for your help ^^

**Comment by kRHYME7** [comment]
Just found out the issue.


what happens when we choose a shell example zsh.


it is appended as
```
some-package #descriptionzsh
```

instead of

```
some-package #description
zsh
```



I added some checks now and it should work. Thank you@Lofibunnygirl ! I managed to debug the install.sh part.
