### ISSUE TITLE
[Bug]: function key not working and hints undone

### ISSUE THREAD

**Issue by Lofibunnygirl** [HyDE-Project/HyDE#48]
Hiya ^^ after getting everything running from hyde project with a clean install. I found that the win key and A no longer opens the apps and also the hints for key strokes look strange.
![20241222_135250](https://github.com/user-attachments/assets/0507366f-0fba-4fa8-918e-957a1dbbeb04)

**Comment by kRHYME7** [comment]
to open the apps it should be `ALT + SPACE`. you can change it to Super + A in keybindings.conf

**Comment by kRHYME7** [comment]
about  the latter issue, hyde needs to fix that by adding descriptions again.

**Comment by Lofibunnygirl** [comment]
Roger that ^^

**Comment by Lofibunnygirl** [comment]
> about the latter issue, hyde needs to fix that by adding descriptions again.
So this will be fixed later on? ^^

**Comment by kRHYME7** [comment]
Yes yes will you test it. The PR is ready but I'm debating myself on the default keybindings. Gotta open a PR later

**Comment by Lofibunnygirl** [comment]
Sure just update? Or..?

**Comment by kRHYME7** [comment]
@Lofibunnygirl try #54

**Comment by kRHYME7** [comment]
@Anshul-007  Will you review this one.

Added an option to group keybindings.
