### ISSUE TITLE
[Bug]: ginormous notifications

### ISSUE THREAD

**Issue by s0m3th1ng-r4nd0m** [HyDE-Project/HyDE#6]
### Description

the notifications take a lot bigger chunk of screen now which on smaller displays looks really bad.  

### Steps to Reproduce

1. fetch changes from this repo
2. apply changes
3. see the really big notifications

### Expected Behavior

maybe normal sized notifications that are not distracting

### Screenshots

![241208_12h22m26s_screenshot](https://github.com/user-attachments/assets/5de0d224-4c56-4bf6-9fd2-cb413afb9964)

### Environment

Display: 1366x768

### Additional Information

Also the battery charged notifications are not themed and are a ugly bright red color.

**Comment by kRHYME7** [comment]
already fixed. remove the height in your dunst.conf. and regenerate it by changing wallpapers it should update the dunstrc

**Comment by s0m3th1ng-r4nd0m** [comment]
oh yeah, i pulled the changes with Hyde-cli and install them with it but i must've done something wrong because they didn't apply properly? anyways, i reinstalled and the notifications are okay now.
