### ISSUE TITLE
[Bug]: Mouse

### ISSUE THREAD

**Issue by JoeArchV** [HyDE-Project/HyDE#63]
There is a bug that makes the mouse very big

**Comment by kRHYME7** [comment]
How big? It's a gtk + Hyprland bug. We can't do anything in here

**Comment by JoeArchV** [comment]
I don't know bro, I haven't looked into the source code for the dolphin bug and I couldn't find anything, but you're more of an expert.

**Comment by kRHYME7** [comment]
dolphin had this issue??

**Comment by rishav12s** [comment]
simply change the size then 

cursors do have size option

**Comment by JoeArchV** [comment]
Yes, I know, but by default it shouldn't be like that.

**Comment by abenezerw** [comment]
Looks like that. Just installed this yesterday btw. Running real smooth. 👌

**Comment by abenezerw** [comment]
![IMG_5378](https://github.com/user-attachments/assets/bf48af48-8d13-4dc6-986a-08436354b3a4)

**Comment by JoeArchV** [comment]
you don't realize

**Comment by JoeArchV** [comment]
What's up with that app?

**Comment by abenezerw** [comment]
Nope. Checked its running on wayland fine. Dont know what to check. Try it. Aur “stremio”

**Comment by kRHYME7** [comment]
Either app is GTK drama or Xwayland. It is rendering XCURSOR. can't fix

**Comment by kRHYME7** [comment]
But maybe try this in your userprefs.conf


```

cursor:no_hardware_cursors = false

```

note this might cause stutter but maybe it can fix your issue

**Comment by JoeArchV** [comment]
can't be added in a non-userprefs file?

**Comment by abenezerw** [comment]
Yup. On nvidia  but currently on igpu which is amd. 
Also happens on the new ghostty terminal 
![IMG_5380](https://github.com/user-attachments/assets/6a2844f1-b3d8-4435-a4de-974fbcf97b83)

**Comment by kRHYME7** [comment]
tried the hardware cursor ??

**Comment by abenezerw** [comment]
yup

**Comment by kRHYME7** [comment]
same issue? Did not happen when using Hyprdots???

**Comment by kRHYME7** [comment]
I can replicate the isssue too cause I have hybrid laptop GPU

**Comment by abenezerw** [comment]
> same issue? Did not happen when using Hyprdots???

Can’t say. Cause I downloaded these two apps after I switched from hyprdots. But I do remember downloading stremio about half a year ago and the mouse was normal.

**Comment by kRHYME7** [comment]
Fundmentally I want a consistent cursor theme so I added these
https://github.com/HyDE-Project/HyDE/blob/d6243beb5ea22d3132e9798644f1373d4ee816d3/Configs/.local/share/hyde/hyprland.conf#L315C1-L319C1
This is not perfect as we are relying on env var and requires a relogin to take effect. but atleast it's consitent.

# without hyde-project change
Without the config above, there will be more issues like inconsitent cursor theme. 
![image](https://github.com/user-attachments/assets/65b7f435-740d-4c59-8e90-3f96055bcb7f)
#### Look this is not the theme I set
![image](https://github.com/user-attachments/assets/e5a04a17-27cc-41ea-a695-0cd25a01043e)

--- 
# With the hyde-project change
Both hyprcursor and XCURSOR themes are consistent, except the size! 
![image](https://github.com/user-attachments/assets/429e156d-51b8-4956-9001-507eacb0aa7a)
![image](https://github.com/user-attachments/assets/1831780c-bc50-4899-855f-b7101a819fb3)


### Now you might need some reference on why this is  happening 
ref: 
https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/#important-notes
https://github.com/hyprwm/Hyprland/issues/6320
https://github.com/hyprwm/Hyprland/issues/2448


---

Now what's your final verdict , 

### +  inconsitent cursor theme and size? 
or 
### + inconsitent cursor size ?

**Comment by kRHYME7** [comment]
Note that XCURSOR only have static size while hyprcursor can change size dynamically.

**Comment by kRHYME7** [comment]
Ugh so you guys are used to hypdots scaling. my bad.

Here's the culprit, thanks @JoeArchV  for pointing out that the variable fixes it.

https://github.com/HyDE-Project/HyDE/blob/d6243beb5ea22d3132e9798644f1373d4ee816d3/Configs/.local/share/hyde/hyprland.conf#L115

I change it to 30 as it works fine with my monitor with x2 scaling.
But I think it is best if we conform to a monitor with x1 scaling instead, assuming this is used widely.
